export const languages = [
  { key: "av", value: "Аварский" },
  { key: "ae", value: "Авестийский" },
  { key: "az", value: "Азербайджанский" },
  { key: "ay", value: "Аймара" },
  { key: "ak", value: "Акан" },
  { key: "sq", value: "Албанский" },
  { key: "am", value: "Амхарский" },
  { key: "en", value: "Английский" },
  { key: "en-UD", value: "Английский (вверх ногами)" },
  { key: "en-AU", value: "Английский, Австралия" },
  { key: "en-AR", value: "Английский, Аравия" },
  { key: "en-BZ", value: "Английский, Белиз" },
  { key: "en-GB", value: "Английский, Великобритания" },
  { key: "en-HK", value: "Английский, Гонконг" },
  { key: "en-DK", value: "Английский, Дания" },
  { key: "en-ZW", value: "Английский, Зимбабве" },
  { key: "en-IN", value: "Английский, Индия" },
  { key: "en-ID", value: "Английский, Индонезия" },
  { key: "en-IE", value: "Английский, Ирландия" },
  { key: "en-CA", value: "Английский, Канада" },
  { key: "en-CB", value: "Английский, Карибы" },
  { key: "en-CN", value: "Английский, Китай" },
  { key: "en-MY", value: "Английский, Малайзия" },
  { key: "en-NZ", value: "Английский, Новая Зеландия" },
  { key: "en-NO", value: "Английский, Норвегия" },
  { key: "en-PR", value: "Английский, Пуэрто-Рико" },
  { key: "en-US", value: "Английский, США" },
  { key: "en-SG", value: "Английский, Сингапур" },
  { key: "en-PH", value: "Английский, Филиппины" },
  { key: "en-SE", value: "Английский, Швеция" },
  { key: "en-ZA", value: "Английский, Южная Африка" },
  { key: "en-JM", value: "Английский, Ямайка" },
  { key: "en-JA", value: "Английский, Япония" },
  { key: "ar", value: "Арабский" },
  { key: "ar-BH", value: "Арабский, Бахрейн" },
  { key: "ar-EG", value: "Арабский, Египет" },
  { key: "ar-YE", value: "Арабский, Йемен" },
  { key: "ar-SA", value: "Арабский, Саудовская Аравия" },
  { key: "an", value: "Арагонский" },
  { key: "hy-AM", value: "Армянский" },
  { key: "frp", value: "Арпитанский" },
  { key: "as", value: "Ассамский" },
  { key: "ast", value: "Астурийский" },
  { key: "tay", value: "Атаял" },
  { key: "aa", value: "Афар" },
  { key: "af", value: "Африкаанс" },
  { key: "ach", value: "Ачоли" },
  { key: "ban", value: "Балийский" },
  { key: "bm", value: "Бамбара" },
  { key: "eu", value: "Баскский" },
  { key: "ba", value: "Башкирский" },
  { key: "be", value: "Белорусский" },
  { key: "bal", value: "Белуджский" },
  { key: "bn", value: "Бенгальский" },
  { key: "bn-IN", value: "Бенгальский, Индия" },
  { key: "ber", value: "Бербер" },
  { key: "bfo", value: "Бирифор" },
  { key: "my", value: "Бирманский" },
  { key: "bi", value: "Бислама" },
  { key: "bh", value: "Бихари" },
  { key: "bg", value: "Болгарский" },
  { key: "bs", value: "Боснийский" },
  { key: "br-FR", value: "Бретон" },
  { key: "val-ES", value: "Валенсийский" },
  { key: "cy", value: "Валлийский" },
  { key: "wa", value: "Валлонский" },
  { key: "hu", value: "Венгерский" },
  { key: "ve", value: "Венда" },
  { key: "vec", value: "Венецианский" },
  { key: "hsb-DE", value: "Верхнелужицкий" },
  { key: "wo", value: "Волоф" },
  { key: "vi", value: "Вьетнамский" },
  { key: "gaa", value: "Га" },
  { key: "haw", value: "Гавайский" },
  { key: "ht", value: "Гаитянский креольский" },
  { key: "gl", value: "Галисийский" },
  { key: "hz", value: "Гереро" },
  { key: "nl-BE", value: "Голландский, Бельгия" },
  { key: "nl-SR", value: "Голландский, Суринам" },
  { key: "got", value: "Готский" },
  { key: "kl", value: "Гренландский" },
  { key: "el", value: "Греческий" },
  { key: "el-CY", value: "Греческий, Кипр" },
  { key: "ka", value: "Грузинский" },
  { key: "gn", value: "Гуарани" },
  { key: "gu-IN", value: "Гуджарати" },
  { key: "gd", value: "Гэльский (Шотландский)" },
  { key: "fa-AF", value: "Дари" },
  { key: "da", value: "Датский" },
  { key: "dz", value: "Дзонг-кэ" },
  { key: "zea", value: "Зеландский" },
  { key: "zu", value: "Зулу" },
  { key: "he", value: "Иврит" },
  { key: "ig", value: "Игбо" },
  { key: "yi", value: "Идиш" },
  { key: "ilo", value: "Илоканский" },
  { key: "id", value: "Индонезийский" },
  { key: "iu", value: "Инуктитут" },
  { key: "ga-IE", value: "Ирландский" },
  { key: "is", value: "Исландский" },
  { key: "es-ES", value: "Испанский" },
  { key: "es-EM", value: "Испанский (современный)" },
  { key: "es-AR", value: "Испанский, Аргентина" },
  { key: "es-BO", value: "Испанский, Боливия" },
  { key: "es-VE", value: "Испанский, Венесуэла" },
  { key: "es-GT", value: "Испанский, Гватемала" },
  { key: "es-HN", value: "Испанский, Гондурас" },
  { key: "es-DO", value: "Испанский, Доминиканская республика" },
  { key: "es-CO", value: "Испанский, Колумбия" },
  { key: "es-CR", value: "Испанский, Коста-Рика" },
  { key: "es-MX", value: "Испанский, Мексика" },
  { key: "es-NI", value: "Испанский, Никарагуа" },
  { key: "es-PA", value: "Испанский, Панама" },
  { key: "es-PY", value: "Испанский, Парагвай" },
  { key: "es-PE", value: "Испанский, Перу" },
  { key: "es-PR", value: "Испанский, Пуэрто-Рико" },
  { key: "es-US", value: "Испанский, США" },
  { key: "es-UY", value: "Испанский, Уругвай" },
  { key: "es-CL", value: "Испанский, Чили" },
  { key: "es-EC", value: "Испанский, Эквадор" },
  { key: "es-SV", value: "Испанский, Эль-Сальвадор" },
  { key: "it", value: "Итальянский" },
  { key: "it-CH", value: "Итальянский, Швейцария" },
  { key: "yo", value: "Йоруба" },
  { key: "kab", value: "Кабильский" },
  { key: "kk", value: "Казахский" },
  { key: "kn", value: "Каннада" },
  { key: "pam", value: "Капампанганский" },
  { key: "ca", value: "Каталанский" },
  { key: "ks", value: "Кашмирский" },
  { key: "ks-PK", value: "Кашмирский, Пакистан" },
  { key: "csb", value: "Кашубский" },
  { key: "kj", value: "Кваньяма" },
  { key: "qya-AA", value: "Квенья" },
  { key: "qu", value: "Кечуа" },
  { key: "rw", value: "Киньяруанда" },
  { key: "ky", value: "Киргизский" },
  { key: "zh-TW", value: "Китайский (традиционный)" },
  { key: "zh-CN", value: "Китайский (упрощенный)" },
  { key: "zh-HK", value: "Китайский традиционный, Гонконг" },
  { key: "zh-MO", value: "Китайский традиционный, Макао" },
  { key: "zh-SG", value: "Китайский традиционный, Сингапур" },
  { key: "quc", value: "Киче" },
  { key: "tlh-AA", value: "Клингонский" },
  { key: "kv", value: "Коми" },
  { key: "kg", value: "Конго" },
  { key: "kok", value: "Конкани" },
  { key: "ko", value: "Корейский" },
  { key: "kw", value: "Корнский" },
  { key: "co", value: "Корсиканский" },
  { key: "xh", value: "Коса" },
  { key: "cr", value: "Кри" },
  { key: "ku", value: "Курдский" },
  { key: "kmr", value: "Курманджи (Курдский)" },
  { key: "km", value: "Кхмерский" },
  { key: "lol", value: "ЛОЛКОТ" },
  { key: "lo", value: "Лао" },
  { key: "la-LA", value: "Латинский" },
  { key: "lv", value: "Латышский" },
  { key: "lij", value: "Лигурийский" },
  { key: "li", value: "Лимбургский" },
  { key: "ln", value: "Лингала" },
  { key: "lt", value: "Литовский" },
  { key: "jbo", value: "Ложбан" },
  { key: "lg", value: "Лугандский" },
  { key: "luy", value: "Лухья" },
  { key: "lb", value: "Люксембургский" },
  { key: "mai", value: "Майтхили" },
  { key: "mk", value: "Македонский" },
  { key: "mg", value: "Малагасийский" },
  { key: "ms", value: "Малайский" },
  { key: "ms-BN", value: "Малайский, Бруней" },
  { key: "ml-IN", value: "Малаялам" },
  { key: "dv", value: "Мальдивский (Дивехи)" },
  { key: "mt", value: "Мальтийский" },
  { key: "mi", value: "Маори" },
  { key: "arn", value: "Мапудунгун" },
  { key: "mr", value: "Маратхи" },
  { key: "mh", value: "Маршалльский" },
  { key: "mn", value: "Монгольский" },
  { key: "mos", value: "Моси" },
  { key: "moh", value: "Мохаук" },
  { key: "gv", value: "Мэнский" },
  { key: "na", value: "Науру" },
  { key: "ng", value: "Ндонга" },
  { key: "de", value: "Немецкий" },
  { key: "de-AT", value: "Немецкий, Австрия" },
  { key: "de-BE", value: "Немецкий, Бельгия" },
  { key: "de-LI", value: "Немецкий, Лихтенштейн" },
  { key: "de-LU", value: "Немецкий, Люксембург" },
  { key: "de-CH", value: "Немецкий, Швейцария" },
  { key: "ne-NP", value: "Непальский" },
  { key: "ne-IN", value: "Непальский, Индия" },
  { key: "pcm", value: "Нигерийский пиджин" },
  { key: "nl", value: "Нидерландский" },
  { key: "nds", value: "Нижнегерманский" },
  { key: "dsb-DE", value: "Нижнелужицкий" },
  { key: "no", value: "Норвежский" },
  { key: "nb", value: "Норвежский букмол" },
  { key: "nn-NO", value: "Норвежский нюнорск" },
  { key: "ii", value: "Носу (Сычуань Йи)" },
  { key: "ny", value: "Ньянджа (Чева)" },
  { key: "oj", value: "Оджибве" },
  { key: "oc", value: "Окситанский" },
  { key: "or", value: "Ория" },
  { key: "om", value: "Оромо" },
  { key: "os", value: "Осетинский" },
  { key: "pi", value: "Пали" },
  { key: "pa-IN", value: "Панджаби" },
  { key: "pa-PK", value: "Панджаби, Пакистан" },
  { key: "pap", value: "Папьяменто" },
  { key: "fa", value: "Персидский" },
  { key: "en-PT", value: "Пиратский английский" },
  { key: "pl", value: "Польский" },
  { key: "pt-PT", value: "Португальский" },
  { key: "pt-BR", value: "Португальский, Бразильский" },
  { key: "ps", value: "Пушту" },
  { key: "rm-CH", value: "Романшский" },
  { key: "ro", value: "Румынский" },
  { key: "rn", value: "Рунди" },
  { key: "ry-UA", value: "Русинский" },
  { key: "ru", value: "Русский" },
  { key: "ru-BY", value: "Русский, Беларусь" },
  { key: "ru-MD", value: "Русский, Молдова" },
  { key: "ru-UA", value: "Русский, Украина" },
  { key: "sg", value: "Санго" },
  { key: "sa", value: "Санскрит" },
  { key: "sat", value: "Сантали" },
  { key: "sc", value: "Сардинский" },
  { key: "ss", value: "Свати" },
  { key: "ceb", value: "Себуанский" },
  { key: "se", value: "Северносаамский" },
  { key: "nso", value: "Северный сото" },
  { key: "crs", value: "Сейшельский креольский" },
  { key: "sh", value: "Сербохорватский" },
  { key: "sr", value: "Сербский (кириллица)" },
  { key: "sr-CS", value: "Сербский (латиница)" },
  { key: "si-LK", value: "Сингальский" },
  { key: "sd", value: "Синдхи" },
  { key: "syc", value: "Сирийский" },
  { key: "sk", value: "Словацкий" },
  { key: "sl", value: "Словенский" },
  { key: "so", value: "Сомалийский" },
  { key: "son", value: "Сонгай" },
  { key: "ckb", value: "Сорани (Курдский)" },
  { key: "sw", value: "Суахили" },
  { key: "sw-KE", value: "Суахили, Кения" },
  { key: "sw-TZ", value: "Суахили, Танзания" },
  { key: "su", value: "Сунданский" },
  { key: "tl", value: "Тагальский" },
  { key: "tg", value: "Таджикский" },
  { key: "ty", value: "Таитянский" },
  { key: "th", value: "Тайский" },
  { key: "tzl", value: "Талосский" },
  { key: "ta", value: "Тамильский" },
  { key: "tt-RU", value: "Татарский" },
  { key: "tw", value: "Тви" },
  { key: "te", value: "Телугу" },
  { key: "kdh", value: "Тем (Котоколи)" },
  { key: "bo-BT", value: "Тибетский" },
  { key: "ti", value: "Тигринья" },
  { key: "tn", value: "Тсвана" },
  { key: "ts", value: "Тсонга" },
  { key: "tr", value: "Турецкий" },
  { key: "tr-CY", value: "Турецкий, Кипр" },
  { key: "tk", value: "Туркменский" },
  { key: "uz", value: "Узбекский" },
  { key: "ug", value: "Уйгурский" },
  { key: "uk", value: "Украинский" },
  { key: "ur-IN", value: "Урду (Индия)" },
  { key: "ur-PK", value: "Урду (Пакистан)" },
  { key: "fo", value: "Фарерский" },
  { key: "fj", value: "Фиджийский" },
  { key: "fil", value: "Филиппинский" },
  { key: "fi", value: "Финский" },
  { key: "vls-BE", value: "Фламандский" },
  { key: "fra-DE", value: "Франконский" },
  { key: "fr", value: "Французский" },
  { key: "fr-BE", value: "Французский, Бельгия" },
  { key: "fr-CA", value: "Французский, Канада" },
  { key: "fr-QC", value: "Французский, Квебек" },
  { key: "fr-LU", value: "Французский, Люксембург" },
  { key: "fr-CH", value: "Французский, Швейцария" },
  { key: "fy-NL", value: "Фризский" },
  { key: "fur-IT", value: "Фриульский" },
  { key: "ff", value: "Фула" },
  { key: "ha", value: "Хауса" },
  { key: "hil", value: "Хилигайнон" },
  { key: "hi", value: "Хинди" },
  { key: "ho", value: "Хири-моту" },
  { key: "hmn", value: "Хмонг" },
  { key: "hr", value: "Хорватский" },
  { key: "ch", value: "Чаморро" },
  { key: "sr-Cyrl-ME", value: "Черногорский (кириллица)" },
  { key: "me", value: "Черногорский (латиница)" },
  { key: "chr", value: "Чероки" },
  { key: "ce", value: "Чеченский" },
  { key: "cs", value: "Чешский" },
  { key: "cv", value: "Чувашский" },
  { key: "sv-SE", value: "Шведский" },
  { key: "sv-FI", value: "Шведский, Финляндия" },
  { key: "sn", value: "Шона" },
  { key: "sco", value: "Шотландский" },
  { key: "ee", value: "Эве" },
  { key: "eo", value: "Эсперанто" },
  { key: "et", value: "Эстонский" },
  { key: "sma", value: "Южносаамский" },
  { key: "nr", value: "Южный ндебеле" },
  { key: "st", value: "Южный сото" },
  { key: "jv", value: "Яванский" },
  { key: "sah", value: "Якутский" },
  { key: "ja", value: "Японский" }
];
